server:
  debug: false
  port: 80
  # proxy: http://localhost:10880
  timeout: 1s

search:
  - name: 百度
    domain: www.baidu.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true
  - name: Bing
    domain: cn.bing.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true
  - name: Google
    domain: www.google.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true
  - name: 微信公众号
    domain: weixin.sogou.com
    weight: 1
    positionWeight: 1
    score: 10
    enable: true

site:
  - domain: www.csdn.com
    weight: 1
    score: 1
  - domain: zhuanlan.zhihu.com
    weight: 1
    score: 1
  - domain: www.yuanbiguo.com
    weight: 1
    score: 1
  - domain: juejin.cn
    weight: 1
    score: 1
  - domain: github.com
    weight: 10
    score: 1
